/**
 * @file gltf_load_test.cpp
 * @brief Headless check of the glTF loader against files with known answers.
 *
 * Why: a loader can produce something that renders plausibly and is still
 * wrong in ways no screenshot shows, such as a joint hanging off the wrong
 * parent, an axis not normalised, or limits read into the wrong fields. The
 * test files are generated by tools/make-test-models.py, so every number
 * checked here is known in advance.
 *
 * What: loads models/test_arm.glb for structure and kinematics,
 * edge_cases.gltf for the repairs, and a set of files that must be refused.
 * The expected end-effector positions are worked out by hand in the comments
 * rather than computed by the code under test.
 *
 * Nothing is uploaded, so no GL context is needed: loaded meshes keep their
 * vertices staged on the CPU, which is also what lets the normals be checked.
 */

#include "gltf_load.h"
#include "robot.h"

#include <math.h>
#include <stdio.h>
#include <string.h>

#ifndef RBT_MODELS_DIR
#error "RBT_MODELS_DIR must name the models directory"
#endif
#ifndef RBT_TEST_DATA_DIR
#error "RBT_TEST_DATA_DIR must name this test's directory"
#endif

/** Positional agreement required between computed and expected points, in metres. */
static const float s_position_tolerance = 1e-4f;

static int s_failures = 0;

/** @brief Record one expectation; a failure is reported and counted, never fatal. */
static void s_check(bool ok, const char *what)
{
    printf("  %-58s %s\n", what, ok ? "pass" : "FAIL");
    if (!ok) {
        s_failures++;
    }
}

/** @brief Index of the joint with this name, or -1. */
static int s_find(const rbt_robot_t *robot, const char *name)
{
    for (size_t i = 0; i < robot->joints.size(); i++) {
        if (strcmp(robot->joints[i].name, name) == 0) {
            return (int)i;
        }
    }
    return -1;
}

/** @brief Pose every movable joint at zero, apart from the one named, then run FK. */
static void s_pose(rbt_robot_t *robot, const char *moved, float moved_deg)
{
    for (rbt_joint_t &joint : robot->joints) {
        joint.angle_deg = 0.0f;
        if (moved != NULL && strcmp(joint.name, moved) == 0) {
            joint.angle_deg = moved_deg;
        }
    }
    rbt_robot_update_fk(robot);
}

/** @brief World position of a joint's frame origin. */
static Vector3f s_origin_of(const rbt_robot_t *robot, const char *name)
{
    const int index = s_find(robot, name);
    return (index < 0) ? Vector3f(NAN, NAN, NAN)
                       : Vector3f(robot->joints[(size_t)index].world_transform.block<3, 1>(0, 3));
}

static bool s_near(const Vector3f &a, const Vector3f &b)
{
    return (a - b).norm() < s_position_tolerance;
}

/** @brief The node tree, the joint data and the meshes of the test arm. */
static void s_case_structure(void)
{
    printf("test_arm.glb, structure:\n");

    rbt_robot_t robot;
    const bool loaded = rbt_gltf_load(&robot, RBT_MODELS_DIR "/test_arm.glb");
    s_check(loaded, "loads");
    if (!loaded) {
        return;
    }

    static const char *const s_order[] = {
        "base", "turntable", "shoulder", "elbow", "wrist", "tool", "finger_left", "finger_right",
    };
    bool order_ok = robot.joints.size() == sizeof(s_order) / sizeof(s_order[0]);
    for (size_t i = 0; order_ok && i < robot.joints.size(); i++) {
        order_ok = strcmp(robot.joints[i].name, s_order[i]) == 0;
    }
    s_check(order_ok, "one frame per node, depth first");

    bool parents_ok = true;
    for (size_t i = 0; i < robot.joints.size(); i++) {
        parents_ok = parents_ok && robot.joints[i].parent < (int)i;
    }
    s_check(parents_ok, "every parent precedes its children");
    s_check(robot.joints[(size_t)s_find(&robot, "finger_left")].parent == s_find(&robot, "tool")
            && robot.joints[(size_t)s_find(&robot, "finger_right")].parent == s_find(&robot, "tool"),
            "both fingers hang off the tool");
    s_check(robot.joints[(size_t)s_find(&robot, "tool")].child_count == 2, "the tool counts two children");

    int movable = 0;
    for (const rbt_joint_t &joint : robot.joints) {
        movable += (joint.type == RBT_JOINT_REVOLUTE) ? 1 : 0;
    }
    s_check(movable == 4, "four revolute joints, the rest fixed");
    s_check(robot.joints[0].type == RBT_JOINT_FIXED, "a node without extras is fixed");

    const rbt_joint_t &turntable = robot.joints[(size_t)s_find(&robot, "turntable")];
    const rbt_joint_t &shoulder  = robot.joints[(size_t)s_find(&robot, "shoulder")];
    const rbt_joint_t &elbow     = robot.joints[(size_t)s_find(&robot, "elbow")];
    const rbt_joint_t &wrist     = robot.joints[(size_t)s_find(&robot, "wrist")];

    s_check(turntable.axis == Vector3f::UnitY() && shoulder.axis == Vector3f::UnitZ(),
            "principal axes come through exactly");
    s_check(s_near(elbow.axis, Vector3f(0.70710678f, 0.0f, 0.70710678f)),
            "a slanted axis is normalised");
    s_check(wrist.axis == -Vector3f::UnitX(), "a negative axis keeps its sign");
    s_check(shoulder.min_angle_deg == -90.0f && shoulder.max_angle_deg == 120.0f,
            "limits land in the right fields");
    s_check(shoulder.default_angle_deg == 30.0f && shoulder.angle_deg == 30.0f,
            "the default angle is also the starting angle");

    char label[48];
    rbt_axis_format(wrist.axis, label, sizeof(label));
    const bool wrist_label = strcmp(label, "-X") == 0;
    rbt_axis_format(elbow.axis, label, sizeof(label));
    s_check(wrist_label && strcmp(label, "0.71, 0.00, 0.71") == 0, "axes are labelled for the panel");

    s_check(robot.meshes.size() == 6, "six meshes: the finger is loaded once");
    s_check(robot.visuals.size() == 7, "seven visuals: the finger is drawn twice");
    s_check(robot.meshes[0].vertices.size() == 24 && robot.meshes[0].indices.size() == 36,
            "16-bit indices are read");

    /* Mesh 3 is the forearm, which the file gives no normals. Each vertex of
     * a flat-faced box belongs to one face only, so its computed normal must
     * be that face's unit normal. */
    bool normals_ok = !robot.meshes[3].vertices.empty();
    for (const rbt_vertex_t &vertex : robot.meshes[3].vertices) {
        const Vector3f n = vertex.normal;
        const float    largest = n.cwiseAbs().maxCoeff();
        normals_ok = normals_ok && fabsf(n.norm() - 1.0f) < 1e-5f && fabsf(largest - 1.0f) < 1e-5f;
    }
    s_check(normals_ok, "missing normals are computed, unit length, per face");

    /* Linear 0.2 encodes to sRGB 1.055 * 0.2^(1/2.4) - 0.055 = 0.48450. */
    s_check(fabsf(turntable.color[1] - 0.48450f) < 1e-3f, "base colours are encoded to sRGB");
}

/** @brief Forward kinematics through a quaternion and a slanted axis. */
static void s_case_kinematics(void)
{
    printf("test_arm.glb, kinematics:\n");

    rbt_robot_t robot;
    if (!rbt_gltf_load(&robot, RBT_MODELS_DIR "/test_arm.glb")) {
        s_check(false, "loads");
        return;
    }

    /* All angles zero: every offset is along +Y and the elbow's quarter turn
     * about Y leaves a Y vector alone, so the tool sits at
     * 0.10 + 0.15 + 0.50 + 0.40 + 0.08 = 1.23. */
    s_pose(&robot, NULL, 0.0f);
    s_check(s_near(s_origin_of(&robot, "tool"), Vector3f(0.0f, 1.23f, 0.0f)), "straight up at rest");

    /* Shoulder 90 degrees about Z at height 0.25: the 0.98 above it turns
     * from +Y to -X. */
    s_pose(&robot, "shoulder", 90.0f);
    s_check(s_near(s_origin_of(&robot, "tool"), Vector3f(-0.98f, 0.25f, 0.0f)), "a principal axis bends the chain");

    /* Elbow 90 degrees about n = (1, 0, 1) / sqrt 2 at height 0.75. Rodrigues
     * on (0, 1, 0) leaves n x v = (-1, 0, 1) / sqrt 2. The elbow frame is a
     * quarter turn about Y, (x, y, z) -> (z, y, -x), giving (1, 0, 1) / sqrt 2.
     * Scaled by the 0.48 above the elbow: 0.48 / sqrt 2 = 0.339411. */
    s_pose(&robot, "elbow", 90.0f);
    s_check(s_near(s_origin_of(&robot, "tool"), Vector3f(0.339411f, 0.75f, 0.339411f)),
            "a slanted axis inside a rotated frame");

    /* The shared finger mesh must follow both its nodes. The fingers sit at
     * x = -+0.025 in the tool frame, but the tool inherits the elbow's quarter
     * turn about Y, (x, y, z) -> (z, y, -x), so in the world they end up at
     * z = +-0.025 instead. */
    s_pose(&robot, NULL, 0.0f);
    s_check(s_near(s_origin_of(&robot, "finger_left"), Vector3f(0.0f, 1.23f, 0.025f))
            && s_near(s_origin_of(&robot, "finger_right"), Vector3f(0.0f, 1.23f, -0.025f)),
            "instances of one mesh sit at their own nodes");
}

/** @brief Articulation data that is wrong but still worth loading. */
static void s_case_repairs(void)
{
    printf("edge_cases.gltf, repairs:\n");

    rbt_robot_t robot;
    if (!rbt_gltf_load(&robot, RBT_TEST_DATA_DIR "/edge_cases.gltf")) {
        s_check(false, "loads");
        return;
    }

    const rbt_joint_t &swapped   = robot.joints[(size_t)s_find(&robot, "swapped")];
    const rbt_joint_t &zero_axis = robot.joints[(size_t)s_find(&robot, "zero_axis")];
    const rbt_joint_t &clamped   = robot.joints[(size_t)s_find(&robot, "clamped_default")];
    const rbt_joint_t &prismatic = robot.joints[(size_t)s_find(&robot, "prismatic")];
    const rbt_joint_t &decoy     = robot.joints[(size_t)s_find(&robot, "decoy")];
    const rbt_joint_t &defaults  = robot.joints[(size_t)s_find(&robot, "defaults")];

    s_check(swapped.min_angle_deg == -90.0f && swapped.max_angle_deg == 90.0f, "swapped limits are put right");
    s_check(zero_axis.axis == Vector3f::UnitZ(), "a zero axis falls back to +Z");
    s_check(clamped.default_angle_deg == 10.0f && clamped.angle_deg == 10.0f,
            "a default outside the limits is clamped");
    s_check(prismatic.type == RBT_JOINT_FIXED, "an unsupported joint type stays fixed");
    s_check(decoy.type == RBT_JOINT_REVOLUTE && decoy.axis == Vector3f::UnitX(),
            "a value spelling a key name is not read as that key");
    s_check(defaults.axis == Vector3f::UnitZ() && defaults.min_angle_deg == -180.0f
            && defaults.max_angle_deg == 180.0f && defaults.default_angle_deg == 0.0f,
            "absent fields take their documented defaults");
}

/** @brief Files that must be refused, leaving the current robot untouched. */
static void s_case_refusals(void)
{
    printf("Refused files:\n");

    rbt_robot_t robot;
    rbt_robot_build_builtin(&robot);
    const size_t joints_before = robot.joints.size();

    const bool missing     = rbt_gltf_load(&robot, RBT_MODELS_DIR "/does_not_exist.glb");
    const bool no_geometry = rbt_gltf_load(&robot, RBT_TEST_DATA_DIR "/no_geometry.gltf");
    const bool not_gltf    = rbt_gltf_load(&robot, RBT_TEST_DATA_DIR "/gltf_load_test.cpp");

    s_check(!missing, "a missing file");
    s_check(!no_geometry, "a file with nothing to draw");
    s_check(!not_gltf, "a file that is not glTF");
    s_check(robot.joints.size() == joints_before && strcmp(robot.name, "Built-in 6-DOF arm") == 0,
            "and the robot is left as it was");
}

int main(void)
{
    s_case_structure();
    s_case_kinematics();
    s_case_repairs();
    s_case_refusals();

    printf("\n%s\n", s_failures == 0 ? "gltf_load: all checks passed" : "gltf_load: FAILURES above");
    return s_failures == 0 ? 0 : 1;
}
